"""document add data type

Revision ID: 1ebab4b7c0ac
Revises: 2b42bffb6730
Create Date: 2024-04-10 10:23:55.926612

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1ebab4b7c0ac'
down_revision = '2b42bffb6730'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_column('data_type')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_type', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('data_type')

    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
